dataset:
  name: VideoDiffFrames
  batch_size: 2
  limit: 0.5
  img_size: 256
  num_frames: 16
  num_workers: 8
  shuffle: False
  pin_memory: False
  train:
#    idspath: datasets/UCF101/frames/train_fps4+8+16+32_ids.json
#    idspath: datasets/UCF101/frames/train_fps32_ids.json
    idspath: datasets/UCF101/frames/train_fps32_ids_horse_makeup.json
    usedfps: ~
    datapath: datasets/UCF101/frames
  val:
#    idspath: datasets/UCF101/frames/valid_fps4+8+16+32_ids.json
    idspath: datasets/UCF101/frames/valid_fps32_ids.json
    usedfps: ~
    datapath: datasets/UCF101/frames

model:
  name: MoCoVQVAE_wCD_shareCB
  pretrain_path: experiments/MoCoVQVAEwCDsCB_UCF_im256_16frames_id4_2022-06-29-13-08-50/MoCoVQVAE_wCD_shareCB_iter250000.pth
  checkpoint_path: ~
  load_strict: False
  fix_encoder: True

  num_hiddens: 256
  num_residual_layers: 4
  num_residual_hiddens: 128

  embedding_dim: 256
  num_embeddings: 16384 # [4096, 9182, ...]

  ds_content: 3
  ds_motion: 5
  ds_identity: 4
  ds_background: 3
  suf_method: conv # [avg_pool, max_pool, conv]
  decoder_type: decoder_woPA
  encoder_mo_type: default

  num_head: 4
  num_group: 4
  time_head: 4

  ABS_weight: 1.0
  MSE_weight: 0.0
  Gen_weight: 0.1

  decay: 0.99
  if_augcb: 2
  commitment_cost: 0.25
  with_lpips: True
  lpips_factor: 1.0

  disc_name: patchwise
  disc_opt:
    input_nc: 48    # 3channel * 16frames
    n_layers: 3
    ndf: 32
    input_formation: concat_c

train:
  device: ~ # the parameter will be given when training
  local_rank: ~ # the parameter will be given when training
  WANDB_OPEN: True
  find_unused_parameters: True

  # model params
  exp_name: MoCoVQVAEwCDsCB_UCF_im256_16frames_id4_woCC_FE
  save_path: experiments/

  # train params
  learning_rate: !!float 3e-4
  LRsche: False

  # steps
  num_epochs: 4000
  num_warmup_steps: 0  # null if want to set 0.1 warm up
  num_training_updates: 100000
  num_validation_steps: 2500
  disc_start_step: 100000
  fullbgid_start: 0
  save_ckpt_per_iter: 5000
